# -*- coding: utf-8 -*-
"""GitHub_API_Data_Collection(wc).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1th8SW15JjC4m5SH3hZmNgJ-0IxWPFcPf

**Sample GitHub_API_Data_Collection**
"""

import requests

url = "https://api.github.com/orgs/microsoft/repos"

url = "https://api.github.com/orgs/microsoft/repos"

response = requests.get(url)

response.status_code

response.json()

len(response.json())

response.json()[0]

response.json()[0]["name"]

response.json()

response.json()[0]["language"]

response.json()[0]["stargazers_count"]

response.json()[0]["forks_count"]

response.json()[0]["updated_at"]

for repo in response.json():
    print(repo["name"])

data = []

for repo in response.json():
    print(repo["name"])

data = []

for repo in response.json():
    data.append({
        "Company": "Microsoft",
        "Repository Name": repo["name"],
        "Description": repo["description"],
        "Language": repo["language"],
        "Stars": repo["stargazers_count"],
        "Forks": repo["forks_count"],
        "Open Issues": repo["open_issues_count"],
        "Watchers": repo["watchers_count"],
        "Created Date": repo["created_at"],
        "Updated Date": repo["updated_at"],
        "Repository URL": repo["html_url"]
    })

data[0]

import pandas as pd
df = pd.DataFrame(data)

df.head()

"""**GitHub_API_Data_Collection**"""

# Imported requests library to make API requests

import requests
import pandas as pd

# List of GitHub organizations to analyze

import requests

companies = [
    "microsoft",
    "google",
    "oracle",
    "ibm",
    "sap",
    "salesforce",
    "snowflakedb",
    "sassoftware"
]

# Created an empty list to store repository data

data = []

# Loop through each company

for company in companies:
    print(company)

company_count = 0

# Loop through API pages (100 repositories per page)
for page in range(1, 11):

    # Create the GitHub API URL
    url = f"https://api.github.com/orgs/{company}/repos?per_page=100&page={page}"

    # Send GET request to the GitHub API
    response = requests.get(url)

    # Convert API response to JSON format
    repos = response.json()

    # Stop if no repositories are returned
    if len(repos) == 0:
        break

    # Loop through each repository
    for repo in repos:
        company_count += 1

print(f"Collected {company_count} repositories from {company}")

import requests

companies = [
    "microsoft",
    "google",
    "oracle",
    "ibm",
    "sap",
    "salesforce",
    "snowflakedb",
    "sassoftware"
]

for company in companies:

    url = f"https://api.github.com/orgs/{company}/repos?per_page=1"

    response = requests.get(url)

    if response.status_code == 200:
        print(f"{company:<15} → VALID ORGANIZATION")
    else:
        print(f"{company:<15} → NOT FOUND / NO ACCESS")

"""Final GitHub_API_Data_Collection"""

# Import required libraries for API calls and data handling

import requests  # used to call GitHub API
import pandas as pd  # used to create and manage dataset
import time  # used to avoid API rate limit issues

import requests

url = "https://api.github.com/orgs/microsoft/repos?per_page=1"

response = requests.get(url, headers=headers)

print(response.status_code)
print(response.text[:300])

# GitHub token for authentication (prevents rate limit issues)

GITHUB_TOKEN = "YOUR_GITHUB_TOKEN_HERE"

# Headers for API request with authentication

headers = {
    "Authorization": f"token {GITHUB_TOKEN}"
}

url = "https://api.github.com/orgs/microsoft/repos?per_page=1"

response = requests.get(url, headers=headers)

print(response.status_code)
print(response.json()[0] if response.status_code == 200 else response.text)

# List of data analytics related companies (GitHub organizations)

companies = [
    "microsoft",      # Microsoft - Power BI, Azure
    "google",         # Google - BigQuery, Looker
    "oracle",         # Oracle - Database & analytics
    "ibm",            # IBM - Cognos, analytics tools
    "sap",            # SAP - Business analytics tools
    "salesforce",     # Salesforce - CRM analytics
    "snowflakedb",    # Snowflake - Cloud data warehouse
    "sassoftware"     # SAS - Statistical analytics
]

# Empty list to store all repository data

data = []

for company in companies:

    print(f"\nCollecting data from {company}...")

    company_count = 0
    page = 1

    while True:

        url = f"https://api.github.com/orgs/{company}/repos"

        params = {
            "per_page": 100,
            "page": page
        }

        response = requests.get(url, headers=headers, params=params)

        # Check API response
        if response.status_code != 200:
            print(f"Error {response.status_code} for {company}")
            break

        repos = response.json()

        # Stop if no more repositories
        if not repos:
            break

        for repo in repos:

            data.append({
                "Company": company,
                "Repository Name": repo["name"],
                "Description": repo["description"],
                "Language": repo["language"],
                "Stars": repo["stargazers_count"],
                "Forks": repo["forks_count"],
                "Open Issues": repo["open_issues_count"],
                "Watchers": repo["watchers_count"],
                "Created Date": repo["created_at"],
                "Updated Date": repo["updated_at"],
                "Repository URL": repo["html_url"]
            })

            company_count += 1

        print(f"Page {page} completed | Total: {company_count}")

        page += 1

    print(f"Collected {company_count} repositories from {company}")

import pandas as pd

df = pd.DataFrame(data)

print("Shape:", df.shape)
df.head()

print("DataFrame shape:", df.shape)
print("Data list length:", len(data))

df.to_excel("test_check.xlsx", index=False)

print("Export done")

df.to_csv("github_analysis.csv", index=False)
df.to_excel("github_analysis.xlsx", index=False)